# Generated by Django 5.1.16.dev20251202143515 on 2026-09-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_no",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Original task number from the spreadsheet.",
                        null=True,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Normal", "Normal"),
                            ("High", "High"),
                            ("Urgent", "Urgent"),
                        ],
                        default="Normal",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_to",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Started", "Not Started"),
                            ("In Progress", "In Progress"),
                            ("On Hold", "On Hold"),
                            ("Complete", "Complete"),
                            ("Cancelled", "Cancelled"),
                            ("Weekly Reports", "Weekly Reports"),
                            ("Upcoming Travel", "Upcoming Travel"),
                            ("Meetings Attended", "Meetings Attended"),
                        ],
                        default="Not Started",
                        max_length=30,
                    ),
                ),
                (
                    "last_update",
                    models.DateField(
                        blank=True,
                        help_text="Date this task's status/notes were last touched.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("date_completed", models.DateField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_archived", "due_date", "task_no"],
            },
        ),
    ]
